original test path: duraspace_fcrepo-cloudsync###duraspace_fcrepo-cloudsync/fcrepo-cloudsync-service/src/test/java/org/duraspace/fcrepo/cloudsync/service/backend/DuraCloudConnectorTest###testPutObject
########## Compile INFO ##########
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync-api:jar:1.1.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-failsafe-plugin is missing. @ org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync:1.1.1-SNAPSHOT, D:\Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\pom.xml, line 336, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync:1.1.1-SNAPSHOT, D:\Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\pom.xml, line 396, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync-service:war:1.1.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:tomcat-maven-plugin is missing. @ line 160, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-failsafe-plugin is missing. @ org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync:1.1.1-SNAPSHOT, D:\Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\pom.xml, line 336, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync:1.1.1-SNAPSHOT, D:\Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\pom.xml, line 396, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync:pom:1.1.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-failsafe-plugin is missing. @ line 336, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 396, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------< org.duraspace.fcrepo-cloudsync:fcrepo-cloudsync-service >-------
[INFO] Building Fedora CloudSync Service 1.1.1-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0-beta-1:enforce (enforce-maven) @ fcrepo-cloudsync-service ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0-beta-1:enforce (default) @ fcrepo-cloudsync-service ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fcrepo-cloudsync-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.1:compile (default-compile) @ fcrepo-cloudsync-service ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fcrepo-cloudsync-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.1:testCompile (default-testCompile) @ fcrepo-cloudsync-service ---
[INFO] Compiling 1 source file to D:\Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[39,38] error: unclosed string literal

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[132,29] error: unclosed string literal

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[132,35] error: ';' expected

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[133,18] error: illegal start of expression

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[133,30] error: ';' expected

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[144,26] error: unclosed string literal

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[144,32] error: ';' expected

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[145,15] error: illegal start of expression

[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[145,24] error: ';' expected

[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.811 s
[INFO] Finished at: 2023-04-29T00:53:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.1:testCompile (default-testCompile) on project fcrepo-cloudsync-service: Compilation failure: Compilation failure: 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[39,38] error: unclosed string literal
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[132,29] error: unclosed string literal
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[132,35] error: ';' expected
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[133,18] error: illegal start of expression
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[133,30] error: ';' expected
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[144,26] error: unclosed string literal
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[144,32] error: ';' expected
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[145,15] error: illegal start of expression
[ERROR] 
[ERROR] \Python\Test_Completion\Promt2Testing\repo_get\approachValidation_repo\duraspace_fcrepo-cloudsync\fcrepo-cloudsync-service\src\test\java\org\duraspace\fcrepo\cloudsync\service\backend\DuraCloudConnectorTest.java:[145,24] error: ';' expected
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
